Switch to hadolint

diff --git a/scripts/lint-dockerfiles b/scripts/lint-dockerfiles
--- a/scripts/lint-dockerfiles
+++ b/scripts/lint-dockerfiles
@@ -2,26 +2,28 @@
 
 set -o pipefail
 
-GIT_ROOT=$(cd "${BASH_SOURCE%/*}" && git rev-parse --show-toplevel)
+REPO_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
 ERROR_RESULTS=0
 
-if command -v dockerfile-utils >/dev/null 2>&1; then
-    echo "Lint Dockerfiles"
-    dockerfiles=$(find "${GIT_ROOT}" -type f -name 'Dockerfile*' -and -not -path "${GIT_ROOT}/vendor/*")
+if command -v hadolint >/dev/null 2>&1; then
+    echo "Lint Dockerfiles" > /dev/stderr
+    # NOTE: We don't attempt to lint Windows Dockerfiles since hadolint doesn't recognize (https://github.com/hadolint/hadolint/issues/371)
+    # the escape directive (https://docs.docker.com/engine/reference/builder/#escape#escape)
+    dockerfiles=$(find "${REPO_ROOT}/dockerfiles" -type f -name 'Dockerfile*' -and -not -name '*servercore*')
     for f in ${dockerfiles}; do
-        f=$(realpath --relative-to="${GIT_ROOT}" "${f}")
-        echo "Linting ${f}"
-        dockerfile-utils lint "${f}" || ((ERROR_RESULTS++))
+        f=$(realpath --relative-to="${REPO_ROOT}" "${f}")
+        echo "Linting ${f}" > /dev/stderr
+        hadolint "${f}" || ((ERROR_RESULTS++))
     done
 else
-    echo "dockerfile-utils is missing, please install it from https://github.com/rcjsuen/dockerfile-utils#installation-instructions"
+    echo "hadolint is missing, please install it from https://github.com/hadolint/hadolint#install" > /dev/stderr
     exit 1
 fi
 
 if [ "${ERROR_RESULTS}" -ne 0 ]; then
-  echo "✖ ${ERROR_RESULTS} lint test(s) failed. Review the log carefully to see full listing."
+  echo "✖ ${ERROR_RESULTS} lint test(s) failed. Review the log carefully to see full listing." > /dev/stderr
   exit 1
 else
-  echo "✔ Linting passed"
+  echo "✔ Linting passed" > /dev/stderr
   exit 0
 fi
